# Generated by Django 5.1.1 on 2024-10-19 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='room',
            table='room',
        ),
    ]
