# Generated by Django 5.1.1 on 2024-10-20 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_alter_room_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='room',
            table='rooms',
        ),
    ]
